### ISSUE TITLE
Movies not rendering

### ISSUE THREAD

**Issue by rodrigodzf** [intro2ddsp/intro2ddsp.github.io#14]
For the introductory section, the additive synthesis section and the physical modelling section, the movies cant be rendered. We get the error:

```python
RuntimeError: Requested MovieWriter (ffmpeg) not available
```

this might be fixed by adding `ffmpeg` to the requirements.

**Comment by jorshi** [comment]
ffmpeg seems to have been the problem. Fixed in #16 and f2c121078c070dcda7f7dd2752ba56ff1d771399
